[tool.poetry]
name = "core"
version = "0.9"
description = "The Django backend for RACTF."
authors = ["RACTF <admins@ractf.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1.1"
boto3 = "^1.14.53"
sentry-sdk = "^0.17.2"
djangorestframework = "^3.11.1"
channels = "^2.4.0"
gunicorn = "^20.0.4"
daphne = "^2.5.0"
django-cors-headers = "^3.5.0"

[tool.poetry.dev-dependencies]
django-silk = "^4.1.0"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
